# Mandatory values to overwrite
alg: ???
env: ???
seeds: ???
compress: ???

# Training parameters
n_stack: 4
total_timesteps: 1e7
log: "./logs/"
tensorboard_log: "./tensorboard_logs/"
verbose: 0
eval:
  n_envs: 1
  eval_freq: 50000
  n_eval_episodes: 3
  deterministic: True

# Default hyperparameters taken from: https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/ppo.yml
PPO:
  n_envs: 8
  n_steps: 128
  n_epochs: 4
  batch_size: 256
  learning_rate: 2.5e-4
  clip_range: 0.1
  vf_coef: 0.5
  ent_coef: 0.01

# Default hyperparameters taken from: https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/qrdqn.yml
QRDQN:
  n_envs: 1
  exploration_fraction: 0.025
  buffer_size: 100000
  optimize_memory_usage: False
